GENOMES_DIR='/home/cmb-panasas2/skchoudh/genomes'
OUT_DIR = '/staging/as/skchoudh/rna/public_Musashi/GSE71333/RNA_Seq'
SRC_DIR = '/home/cmb-panasas2/skchoudh/github_projects/clip_seq_pipeline/scripts'
RAWDATA_DIR ='/staging/as/skchoudh/dna/public_Musashi/GSE71333/RNA_Seq'
GENOME_BUILD = 'mm10'
GENOME_FASTA = GENOMES_DIR + '/' + GENOME_BUILD + '/fasta/'+ GENOME_BUILD+ '.fa'
STAR_INDEX = GENOMES_DIR + '/' + GENOME_BUILD + '/star_annotated'
GTF = GENOMES_DIR + '/' + GENOME_BUILD + '/annotation/' + 'gencode.vM11.annotation.gtf'
GENE_NAMES = GENOMES_DIR + '/' + GENOME_BUILD + '/annotation/' + GENOME_BUILD+'_gene_names_stripped.tsv'
GENE_LENGTHS = GENOMES_DIR + '/' + GENOME_BUILD + '/annotation/' + 'gencode.vM11.coding_lengths.tsv'  #+ GENOME_BUILD+'_gene_lengths.tsv'
DESIGN_FILE = '/staging/as/skchoudh/dna/public_Musashi/GSE71333/RNA_Seq/design.txt'
ANNOT_DIR = '/home/cmb-panasas2/skchoudh/github_projects/gencode_regions/data/GRCm38/vM11/'
#GENE_BED = ANNOT_DIR + 'genes.bed'

HTSEQ_STRANDED = 'reverse'
GENE_BED = GENOMES_DIR + '/' + GENOME_BUILD + '/annotation/' + 'gencode.vM11.genes.bed'  #+ GENOME_BUILD+'_gene_lengths.tsv'
